# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jhon Vincent Jose
title: Graphic Designer
email: josejhonvincent.m@gmail.com
website: https://josejhonvincent.github.io/myportfolio/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: roundcheese_
github_username:  josejhonvincent
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: round.cheese
linkedin_username: josejhonvincentm
# xing_username: jekyll
# pinterest_username: jekyll

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
 # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a self-motivated and creative individual with over three years of experience in freelance work. 
  I have a passion for graphic design and I am always looking for new challenges and opportunities to hone my skills.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Arellano University Jose Abad Santos
        caption: 2016 - 2017
        sub_title: Bachelor of Science in Information Technology
        title: STI College Parañaque
        caption: ​​2015 - 2016
        sub_title: Bachelor of Science in Information Technology
        
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Freelance
        # link_text: boringcompany.com
        sub_title: Graphic Designer
        caption: March 2020 - present
        quote: >
          - Remained committed to producing quality content in accordance with deadlines.
          - Utilized Adobe Creative Suite to design logos, brochures, websites, advertisements, and other visual elements.
          - Created Innovative designs that effectively communicated the brand's message to target audience.
          - Worked to ensure that client brand standards were upheld.
          - Completed 50+ graphic design projects for small businesses and big corporations.

        title: Social Media Administrator
        # link_text: boringcompany.com
        sub_title: Team PikaJems
        caption: May 2020 - 2022
        quote: >
          - Organizes all social media posts.
          - Created designs and layouts.
          - Conceptualized and executed design of digital campaigns.     

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
